version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: johnny
      MONGO_INITDB_ROOT_PASSWORD: Yonni
  ui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: johnny 
      ME_CONFIG_MONGODB_ADMINPASSWORD: Yonni
      ME_CONFIG_MONGODB_SERVER: mongo