version: '3.7'

services:
  client:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - server
    # command: 'bash command to run before the cmd of the container'
    restart: on_failure
    # deploy:
    #   replicas: 3
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:3000/health || exit 1"]
      interval: 3s
      retries: 5
      start_period: 60s

  server:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5' # limit the container 
          memory: '256M'
        reservations:
          cpus: '0.2'
          memory: '128M'



  mongo:
    image: mongo:4.0-xenial
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - todo:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
    secrets:
      - db_password

volumes:
  todo:

secrets:
  db_password:
    file: secret1.txt